# Generated by Django 5.1 on 2024-08-30 13:24

import auxiliaries.auxiliaries_methods
import datetime
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_content_update', models.BooleanField(default=False)),
                ('on_maintenance', models.BooleanField(default=False)),
                ('experimental', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dynamic Settings',
                'verbose_name_plural': 'Dynamic Settings',
            },
        ),
        migrations.CreateModel(
            name='OwnerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('tax_number', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Owner Data',
                'verbose_name_plural': 'Owner Data',
            },
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=128, prefix='')),
                ('for_email', models.EmailField(max_length=254, unique=True)),
                ('until', models.DateTimeField(default=datetime.datetime(2024, 8, 30, 19, 24, 50, 365980))),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordCase',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=32, prefix='', primary_key=True, serialize=False)),
                ('until', models.DateTimeField(default=auxiliaries.auxiliaries_methods.get_until_time)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], default='en-us', max_length=10)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
