# Generated by Django 5.0.3 on 2024-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('it', 'Italian'), ('gr', 'Greek'), ('de', 'Deutch'), ('es', 'Spanish'), ('ru', 'Russian')], default='en-us', max_length=10),
        ),
    ]
