# Generated by Django 5.0.3 on 2024-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_alter_userprofile_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_content_update', models.BooleanField(default=False)),
                ('on_maintenance', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
