# Generated by Django 5.0.3 on 2024-07-08 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0006_resetpasswordcases'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordcases',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='resetpasswordcases',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 8, 15, 5, 7, 391510, tzinfo=datetime.timezone.utc)),
        ),
    ]
