# Generated by Django 5.0.7 on 2024-07-17 19:11

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0007_resetpasswordcases_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordcases',
            name='until',
            field=models.DateTimeField(default=timezone.now()),
        ),
    ]
