# Generated by Django 5.0.7 on 2024-07-17 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0007_resetpasswordcases_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpasswordcases',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 22, 11, 49, 429572, tzinfo=datetime.timezone.utc)),
        ),
    ]
