# Generated by Django 5.0.7 on 2024-08-01 09:17

import django.db.models.deletion
import shortuuid.django_fields
import stuff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_alter_resetpasswordcases_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('tax_number', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Owner Data',
                'verbose_name_plural': 'Owner Data',
            },
        ),
        migrations.AlterModelOptions(
            name='dynamicsettings',
            options={'verbose_name': 'Dynamic Settings', 'verbose_name_plural': 'Dynamic Settings'},
        ),
        migrations.CreateModel(
            name='ResetPasswordCase',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=16, max_length=32, prefix='', primary_key=True, serialize=False)),
                ('until', models.DateTimeField(default=stuff.models.get_until_time)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ResetPasswordCases',
        ),
    ]
