# Generated by Django 5.0.7 on 2024-08-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0010_ownerdata_alter_resetpasswordcase_until_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicsettings',
            options={'verbose_name': 'Dynamic Settings', 'verbose_name_plural': 'Dynamic Settings'},
        ),
        migrations.AlterModelOptions(
            name='ownerdata',
            options={'verbose_name': 'Owner Data', 'verbose_name_plural': 'Owner Data'},
        ),
    ]
