# Generated by Django 5.1 on 2024-08-23 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0012_emailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtoken',
            name='for_email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 24, 0, 24, 52, 891805, tzinfo=datetime.timezone.utc)),
        ),
    ]
