# Generated by Django 5.1 on 2024-08-25 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0013_emailtoken_for_email_alter_emailtoken_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 13, 41, 45, 300125, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], default='ru-RU', max_length=10),
        ),
    ]
