# Generated by Django 5.1 on 2024-08-27 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0015_dynamicsettings_experimental_alter_emailtoken_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='until',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 13, 6, 48, 640811, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('ru', 'Russian')], default='en-us', max_length=10),
        ),
    ]
