# Generated by Django 5.1 on 2024-08-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[('women', 'WOMEN'), ('men', 'MEN'), ('unisex', '_(UNISEX)'), ('misc', 'MISC')], max_length=6, null=True),
        ),
    ]
