# Generated by Django 5.1 on 2024-08-27 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_color_options_alter_size_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_set', to='store.stock'),
        ),
    ]
