# Generated by Django 5.0.3 on 2024-05-05 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_stock_discount_remove_stock_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockImage',
            new_name='CarouselImage',
        ),
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'verbose_name': 'Carousel Image', 'verbose_name_plural': 'Carousel Images'},
        ),
        migrations.RemoveField(
            model_name='carouselimage',
            name='stock',
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
            preserve_default=False,
        ),
    ]
