# Generated by Django 5.0.3 on 2024-06-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_item_discount_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код категории'),
        ),
    ]
