# Generated by Django 5.1 on 2024-08-31 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(upload_to='product_images/1/carousel_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='store.item'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/1/category_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image_men',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/1/category_images/men', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image_unisex',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/1/category_images/unisex', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image_women',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/1/category_images/women', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collection_image',
            field=models.ImageField(null=True, upload_to='product_images/1/collection_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение коллекции'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.CharField(blank=True, choices=[('women', 'WOMEN'), ('men', 'MEN'), ('unisex', 'UNISEX'), ('misc', 'MISC')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='product_images/1/item_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение'),
        ),
    ]
