# Generated by Django 5.0.3 on 2024-06-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
