# Generated by Django 5.0.3 on 2024-04-17 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_color_item_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AddField(
            model_name='category',
            name='collection_image',
            field=models.ImageField(null=True, upload_to='product_images/category_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Изображение категории'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_image',
            field=models.ImageField(null=True, upload_to='product_images/collection_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Изображение коллекции'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images/item_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Изображение'),
        ),
    ]
