# Generated by Django 5.0.3 on 2024-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='stock_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
