# Generated by Django 5.1 on 2024-09-09 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_collectioncarouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_image_men',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/1/collection_images/men', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_image_unisex',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/1/collection_images/unisex', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_image_women',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/1/collection_images/women', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
