# Generated by Django 5.0.3 on 2024-04-18 18:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/1/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item', verbose_name='Картинка товара')),
            ],
            options={
                'verbose_name': 'Round Image',
                'verbose_name_plural': 'Round Images',
            },
        ),
    ]
