# Generated by Django 5.0.7 on 2024-07-28 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('store', '0012_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='session_key',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
