# Generated by Django 5.0.3 on 2024-04-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_roundimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='collection_image',
            new_name='category_image',
        ),
    ]
