# Generated by Django 5.0.3 on 2024-04-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_item_size_size_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundimage',
            name='item',
        ),
        migrations.RemoveField(
            model_name='size',
            name='item',
        ),
        migrations.AddField(
            model_name='roundimage',
            name='item',
            field=models.ManyToManyField(to='store.item', verbose_name='Картинка товара'),
        ),
        migrations.AddField(
            model_name='size',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='store.item', verbose_name='Товар'),
        ),
    ]
