# Generated by Django 5.0.3 on 2024-04-24 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_roundimage_item_remove_size_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='item',
        ),
        migrations.RemoveField(
            model_name='roundimage',
            name='item',
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.size')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sizes',
            field=models.ManyToManyField(related_name='items', through='store.ItemSize', to='store.size'),
        ),
        migrations.AddField(
            model_name='roundimage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_images', to='store.item', verbose_name='Картинка товара'),
        ),
    ]
