# Generated by Django 5.0.3 on 2024-04-24 11:35

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_size_item_remove_roundimage_item_itemsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='link',
            field=models.CharField(max_length=256, null=True, validators=[store.models.validation_link], verbose_name='Ссылка на коллекцию'),
        ),
    ]
