# Generated by Django 5.0.3 on 2024-04-24 14:11

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_collection_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None, verbose_name='Цвет')),
            ],
        ),
        migrations.AlterModelOptions(
            name='itemsize',
            options={'verbose_name': 'Item size', 'verbose_name_plural': 'Item sizes'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(related_name='items', through='store.ItemColor', to='store.color'),
        ),
    ]
