# Generated by Django 5.0.3 on 2024-04-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_color_alter_itemsize_options_remove_item_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='itemcolor',
            options={'verbose_name': 'Item color', 'verbose_name_plural': 'Item colors'},
        ),
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='colors',
        ),
    ]
