# Generated by Django 5.0.3 on 2024-04-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_type_category_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
