# Generated by Django 5.0.3 on 2024-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товаров этого цвета'),
        ),
        migrations.AddField(
            model_name='itemsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товаров этого размера'),
        ),
    ]
