# Generated by Django 5.0.3 on 2024-04-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_color_quantity_itemsize_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='color',
            name='quantity',
        ),
        migrations.AddField(
            model_name='itemsize',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color'),
        ),
        migrations.DeleteModel(
            name='ItemColor',
        ),
    ]
