# Generated by Django 5.0.3 on 2024-04-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_item_colors_remove_color_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='hex',
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество товаров этого размера и цвета'),
        ),
    ]
