# Generated by Django 5.0.3 on 2024-04-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_rename_color_color_hex_alter_itemsize_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemsize',
            unique_together={('size', 'item', 'color')},
        ),
    ]
