# Generated by Django 5.0.3 on 2024-04-24 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_itemsize_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemSize',
            new_name='ItemSizeColor',
        ),
    ]
