# Generated by Django 5.0.3 on 2024-04-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_itemsize_itemsizecolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='name',
        ),
    ]
