# Generated by Django 5.0.3 on 2024-04-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_rename_size_size_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sizes',
        ),
        migrations.CreateModel(
            name='SizeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.color')),
            ],
            options={
                'verbose_name': 'Size and color',
                'verbose_name_plural': 'Sizes and colors',
            },
        ),
        migrations.AlterUniqueTogether(
            name='itemsizecolor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='item',
            name='sizes_colors',
            field=models.ManyToManyField(related_name='items', through='store.ItemSizeColor', to='store.sizecolor'),
        ),
        migrations.AddField(
            model_name='itemsizecolor',
            name='size_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.sizecolor'),
        ),
        migrations.AlterUniqueTogether(
            name='itemsizecolor',
            unique_together={('size_color', 'item')},
        ),
        migrations.RemoveField(
            model_name='itemsizecolor',
            name='color',
        ),
        migrations.RemoveField(
            model_name='itemsizecolor',
            name='size',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
