# Generated by Django 5.0.3 on 2024-04-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_item_sizes_sizecolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizecolor',
            name='name',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='sizecolor',
            unique_together={('name', 'color')},
        ),
    ]
