# Generated by Django 5.0.3 on 2024-04-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_itemsizecolor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
