version: "3.9"

services:
  postgresql:
    image: postgres:latest
    restart: always
    env_file:
      - postgres-files/prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: timshee/
      dockerfile: prod.Dockerfile
    restart: always
    env_file:
      - timshee/prod.env
    volumes:
      - prod.volume:/home/timshee_store_app/app/staticfiles
      - prod.volume-images:/home/timshee_store_app/app/media/product_images
    command: ["python", "/home/timshee_store_app/app/entrypoint.py"]
    depends_on:
      - postgresql

  nginx:
    build:
      context: nginx/
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - "8111:80"
      - "443:443"
    volumes:
      - prod.volume:/home/timshee_store_app/app/staticfiles
      - prod.volume-images:/home/timshee_store_app/app/media/product_images
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - django

volumes:
  prod.volume:
  prod.volume-images:
  postgres_data: