entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

tls:
  certificates:
    - certFile: "/etc/ssl/certs/fullchain.pem"
      keyFile: "/etc/ssl/private/privkey.pem"