version: "3.9"

services:
  reverse_proxy:
    image: traefik:v3.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=heavycream9090@icloud.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=timshee_store
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mjml:
    image: danihodovic/mjml-server
    platform: linux/amd64

  django:
    image: pavelbeard/django:unstable
    platform: linux/amd64
    environment:
      - ALLOWED_ORIGINS=https://heavycream.es,http://77.238.243.142:8112
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=heavycream9090@icloud.com
      - DJANGO_SETTINGS_DEBUG_MODE=0
      - DJANGO_SETTINGS_UNSTABLE_MODE=1
      - DJANGO_SETTINGS_PRODUCTION_MODE=0
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8112
      - POSTGRES_DB_NAME=timshee_store
      - POSTGRES_DB_USER=main
      - POSTGRES_DB_PORT=5432
      - ACCOUNT_ID=${ACCOUNT_ID}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - MJML_APP_ID=${MJML_APP_ID}
      - MJML_APP_KEY=${MJML_APP_KEY}
      - MJML_OWN_SERVER_URL=${MJML_OWN_SERVER_URL}
      - CLIENT_REDIRECT=https://heavycream.es
    labels:
      # reverse proxy
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`heavycream.es`) && PathPrefix(`/api`) || PathPrefix(`/admin`) || PathPrefix(`/backend/static`) || PathPrefix(`/backend/media`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=myresolver"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - unstable.volume:/home/timshee_store_app/app/staticfiles
      - unstable-image.volume:/home/timshee_store_app/app/media/product_images
    command: ["python", "/home/timshee_store_app/app/entrypoint.py"]
    depends_on:
      - mjml
      - postgresql
    restart: on-failure

  frontend:
    image: pavelbeard/frontend:unstable
    platform: linux/amd64
    labels:
      # reverse proxy
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`heavycream.es`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      # watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - unstable.volume:/home/timshee_store_app/app/staticfiles
      - unstable-image.volume:/home/timshee_store_app/app/media/product_images
    depends_on:
      - django
    restart: on-failure

volumes:
  letsencrypt:
  unstable.volume:
  unstable-image.volume:
  postgres_data: