version: "3.9"

services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=timshee_store
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mjml:
    image: danihodovic/mjml-server
    platform: linux/amd64

  django:
    build:
      context: timshee/
      dockerfile: unstable.Dockerfile
    environment:
      - ALLOWED_ORIGINS=https://77.238.243.142
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=heavycream9090@icloud.com
      - DJANGO_SETTINGS_DEBUG_MODE=0
      - DJANGO_SETTINGS_UNSTABLE_MODE=1
      - DJANGO_SETTINGS_PRODUCTION_MODE=0
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8112
      - POSTGRES_DB_NAME=timshee_store
      - POSTGRES_DB_USER=main
      - POSTGRES_DB_PORT=5432
      - ACCOUNT_ID=${ACCOUNT_ID}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - MJML_APP_ID=${MJML_APP_ID}
      - MJML_APP_KEY=${MJML_APP_KEY}
      - MJML_OWN_SERVER_URL=${MJML_OWN_SERVER_URL}
      - CLIENT_REDIRECT=https://77.238.243.142
    volumes:
      - unstable.volume:/home/timshee_store_app/app/staticfiles
      - unstable-image.volume:/home/timshee_store_app/app/media/product_images
    command: ["python", "/home/timshee_store_app/app/entrypoint.py"]
    depends_on:
      - postgresql
    restart: on-failure

  load_balancer:
    build:
      context: load_balancer/
      dockerfile: unstable.Dockerfile
    ports:
      - "8112:80"
      - "443:443"
    volumes:
      - unstable.volume:/home/timshee_store_app/app/staticfiles
      - unstable-image.volume:/home/timshee_store_app/app/media/product_images
    depends_on:
      - django
    restart: on-failure

  frontend:
    build:
      context: frontend/
      dockerfile: unstable.Dockerfile
    volumes:
      - unstable.volume:/home/timshee_store_app/app/staticfiles
      - unstable-image.volume:/home/timshee_store_app/app/media/product_images
    depends_on:
      - load_balancer
    restart: on-failure

volumes:
  unstable.volume:
  unstable-image.volume:
  postgres_data: