# Generated by Django 5.1 on 2024-09-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_currencymultiplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='add_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
