# Generated by Django 5.2.5 on 2025-08-12 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(help_text='Unique identifier for this template', max_length=100, unique=True, verbose_name='Template name')),
                ('subject', models.CharField(help_text='Subject line for the notification. Supports Django template syntax.', max_length=255, verbose_name='Subject')),
                ('content', models.TextField(help_text='Content of the notification. Supports Django template syntax.', verbose_name='Content')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], default='email', max_length=20, verbose_name='Notification type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and can be used', verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('subject', models.CharField(help_text='Rendered subject of the notification', max_length=255, verbose_name='Subject')),
                ('content', models.TextField(help_text='Rendered content of the notification', verbose_name='Content')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification')], max_length=20, verbose_name='Notification type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='JSON data used to render the notification', verbose_name='Context data')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this notification', verbose_name='Is read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was marked as read', null=True, verbose_name='Read at')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When this notification should be sent', null=True, verbose_name='Scheduled for')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When this notification was sent', null=True, verbose_name='Sent at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('template', models.ForeignKey(blank=True, help_text='Template used to generate this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('to_email', models.EmailField(help_text='Recipient email address', max_length=254, verbose_name='To email')),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=254, verbose_name='From email')),
                ('cc_emails', models.JSONField(blank=True, default=list, help_text='List of CC email addresses', verbose_name='CC emails')),
                ('bcc_emails', models.JSONField(blank=True, default=list, help_text='List of BCC email addresses', verbose_name='BCC emails')),
                ('html_content', models.TextField(blank=True, help_text='HTML version of the email content', verbose_name='HTML content')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment file paths or URLs', verbose_name='Attachments')),
                ('delivery_attempts', models.PositiveIntegerField(default=0, help_text='Number of times delivery was attempted', verbose_name='Delivery attempts')),
                ('last_delivery_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Last delivery attempt')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the email was successfully delivered', null=True, verbose_name='Delivered at')),
                ('bounce_reason', models.TextField(blank=True, help_text='Reason for email bounce if delivery failed', verbose_name='Bounce reason')),
                ('email_provider_id', models.CharField(blank=True, help_text='ID from email service provider (SendGrid, SES, etc.)', max_length=255, verbose_name='Email provider ID')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_details', to='notifications.notification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('device_token', models.CharField(help_text='Push notification device token', max_length=255, verbose_name='Device token')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20, verbose_name='Platform')),
                ('badge_count', models.PositiveIntegerField(blank=True, help_text='Badge count for the app icon', null=True, verbose_name='Badge count')),
                ('sound', models.CharField(blank=True, help_text='Sound to play with the notification', max_length=100, verbose_name='Sound')),
                ('category', models.CharField(blank=True, help_text='Notification category for grouping', max_length=100, verbose_name='Category')),
                ('action_url', models.URLField(blank=True, help_text='URL to open when notification is tapped', verbose_name='Action URL')),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Additional custom data for the push notification', verbose_name='Custom data')),
                ('delivery_attempts', models.PositiveIntegerField(default=0, verbose_name='Delivery attempts')),
                ('last_delivery_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Last delivery attempt')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('push_provider_id', models.CharField(blank=True, help_text='ID from push service provider (FCM, APNS, etc.)', max_length=255, verbose_name='Push provider ID')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_details', to='notifications.notification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': 'Push Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('to_phone', models.CharField(help_text='Recipient phone number in international format', max_length=20, verbose_name='To phone number')),
                ('from_phone', models.CharField(blank=True, help_text='Sender phone number or short code', max_length=20, verbose_name='From phone number')),
                ('delivery_attempts', models.PositiveIntegerField(default=0, verbose_name='Delivery attempts')),
                ('last_delivery_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Last delivery attempt')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('sms_provider_id', models.CharField(blank=True, help_text='ID from SMS service provider (Twilio, etc.)', max_length=255, verbose_name='SMS provider ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cost of sending this SMS', max_digits=10, null=True, verbose_name='Cost')),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_details', to='notifications.notification', verbose_name='Notification')),
            ],
            options={
                'verbose_name': 'SMS Notification',
                'verbose_name_plural': 'SMS Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email notifications enabled')),
                ('email_order_updates', models.BooleanField(default=True, verbose_name='Order update emails')),
                ('email_promotions', models.BooleanField(default=True, verbose_name='Promotional emails')),
                ('email_security', models.BooleanField(default=True, verbose_name='Security emails')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS notifications enabled')),
                ('sms_order_updates', models.BooleanField(default=False, verbose_name='Order update SMS')),
                ('sms_security', models.BooleanField(default=True, verbose_name='Security SMS')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push notifications enabled')),
                ('push_order_updates', models.BooleanField(default=True, verbose_name='Order update push notifications')),
                ('push_promotions', models.BooleanField(default=False, verbose_name='Promotional push notifications')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='In-app notifications enabled')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text="Don't send notifications during quiet hours", verbose_name='Quiet hours enabled')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text="Start time for quiet hours (user's timezone)", null=True, verbose_name='Quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text="End time for quiet hours (user's timezone)", null=True, verbose_name='Quiet hours end')),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone for scheduling notifications", max_length=50, verbose_name='Timezone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Notification Preferences',
                'verbose_name_plural': 'User Notification Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status'], name='notificatio_status_d92267_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_for'], name='notificatio_schedul_cf7340_idx'),
        ),
    ]
