# Generated by Django 5.0.3 on 2024-04-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shipping_address_alter_order_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='cart_items',
        ),
    ]
