# Generated by Django 5.0.3 on 2024-04-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_anonymouscart_anonymouscartitem'),
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
