# Generated by Django 5.0.3 on 2024-04-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_anonymouscart_anonymouscartitem'),
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        # migrations.CreateModel(
        #     name='AnonymousAddress',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('street', models.CharField(max_length=255)),
        #         ('interior', models.CharField(max_length=255)),
        #         ('postal_code', models.CharField(max_length=20)),
        #         ('email', models.EmailField(max_length=254)),
        #         ('phone_number', models.CharField(max_length=20)),
        #         ('additional_data', models.TextField(blank=True, null=True)),
        #         ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.city')),
        #         ('phone_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.countryphonecode')),
        #     ],
        #     options={
        #         'verbose_name': 'Address',
        #         'verbose_name_plural': 'Addresses',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='AnonymousOrder',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('status', models.CharField(choices=[('created', 'CREATED'), ('pending_for_pay', 'PENDING FOR PAY'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='pending_for_pay', max_length=20)),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #         ('cart_items', models.ManyToManyField(to='cart.cartitem')),
        #         ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.anonymousaddress')),
        #     ],
        #     options={
        #         'verbose_name': 'Order',
        #         'verbose_name_plural': 'Orders',
        #     },
        # ),
    ]
