# Generated by Django 5.0.3 on 2024-04-26 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_options_anonymousaddress_anonymousorder'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='set_as_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymousaddress',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AddField(
            model_name='anonymousorder',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
