# Generated by Django 5.0.3 on 2024-04-26 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_address_set_as_primary_anonymousaddress_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='set_as_primary',
            new_name='as_primary',
        ),
    ]
