# Generated by Django 5.0.3 on 2024-04-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_set_as_primary_address_as_primary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='interior',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='address2',
        ),
        # migrations.RenameField(
        #     model_name='anonymousaddress',
        #     old_name='interior',
        #     new_name='address1',
        # ),
        # migrations.RenameField(
        #     model_name='anonymousaddress',
        #     old_name='street',
        #     new_name='address2',
        # ),
    ]
