# Generated by Django 5.0.3 on 2024-04-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_anonymouscartitem_options'),
        ('order', '0011_rename_interior_address_address1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymousaddress',
            options={'verbose_name': 'Anonymous address', 'verbose_name_plural': 'Anonymous addresses'},
        ),
        migrations.AlterModelOptions(
            name='anonymousorder',
            options={'verbose_name': 'Anonymous order', 'verbose_name_plural': 'Anonymous orders'},
        ),
        migrations.AlterField(
            model_name='anonymousorder',
            name='cart_items',
            field=models.ManyToManyField(to='cart.anonymouscartitem'),
        ),
    ]
