# Generated by Django 5.0.3 on 2024-04-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_address_first_name_address_last_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Province',
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='order.province'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
