# Generated by Django 5.0.3 on 2024-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_province_options_alter_address_province_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='anonymousorder',
        #     name='order_number',
        #     field=models.CharField(default='10000-AN', max_length=255, unique=True),
        # ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='10000-AU', max_length=255, unique=True),
        ),
    ]
