# Generated by Django 5.0.3 on 2024-05-21 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_shippingmethod_anonymousorder_shipping_method_and_more'),
        ('sessions', '0001_initial'),
    ]
