# Generated by Django 5.0.3 on 2024-05-30 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_anonymousorder_status_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='anonymousorder',
        #     name='shipping_address',
        # ),
        # migrations.RemoveField(
        #     model_name='anonymousorder',
        #     name='session',
        # ),
        # migrations.RemoveField(
        #     model_name='anonymousorder',
        #     name='shipping_method',
        # ),
        # migrations.AddField(
        #     model_name='address',
        #     name='session_key',
        #     field=models.CharField(blank=True, max_length=40, null=True),
        # ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # migrations.DeleteModel(
        #     name='AnonymousAddress',
        # ),
        # migrations.DeleteModel(
        #     name='AnonymousOrder',
        # ),
    ]
