# Generated by Django 5.0.3 on 2024-05-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_remove_anonymousorder_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
