# Generated by Django 5.0.3 on 2024-06-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_order_refund_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('pending_for_pay', 'PENDING FOR PAY'), ('processing', 'PROCESSING'), ('delivering', 'DELIVERING'), ('completed', 'COMPLETED'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], default='created', max_length=20),
        ),
    ]
