# Generated by Django 5.0.3 on 2024-06-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0029_orderitem_order_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_reason',
            field=models.CharField(blank=True, choices=[('created', 'CREATED'), ('pending_for_pay', 'PENDING FOR PAY'), ('processing', 'PROCESSING'), ('delivering', 'DELIVERING'), ('completed', 'COMPLETED'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], max_length=255, null=True),
        ),
    ]
