# Generated by Django 5.0.3 on 2024-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_address_last_name_address_session_key_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
