# Generated by Django 5.0.3 on 2024-06-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_continent_country_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
