# Generated by Django 5.0.3 on 2024-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_alter_address_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('pending_for_pay', 'PENDING FOR PAY'), ('processing', 'PROCESSING'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('completed', 'COMPLETED'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='refund_reason',
            field=models.CharField(blank=True, choices=[('created', 'CREATED'), ('pending_for_pay', 'PENDING FOR PAY'), ('processing', 'PROCESSING'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('completed', 'COMPLETED'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], max_length=255, null=True),
        ),
    ]
