# Generated by Django 5.0.3 on 2024-06-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_alter_order_status_alter_orderitem_refund_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='non_refundable',
            field=models.BooleanField(default=False),
        ),
    ]
