# Generated by Django 5.0.7 on 2024-08-01 09:17

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_order_non_refundable'),
        ('sessions', '0001_initial'),
        ('store', '0012_alter_item_price'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='address',
        #     name='session_key',
        # ),
        # migrations.RemoveField(
        #     model_name='order',
        #     name='ordered_items',
        # ),
        # migrations.RemoveField(
        #     model_name='order',
        #     name='session_key',
        # ),
        # migrations.RemoveField(
        #     model_name='orderitem',
        #     name='refund_reason',
        # ),
        migrations.AddField(
            model_name='address',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AddField(
            model_name='order',
            name='second_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=16, max_length=32, prefix=''),
        ),
        migrations.AddField(
            model_name='order',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(related_name='order_items', through='order.OrderItem', to='store.stock'),
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('refund_reason', models.CharField(blank=True, choices=[('created', 'CREATED'), ('pending_for_pay', 'PENDING FOR PAY'), ('processing', 'PROCESSING'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('completed', 'COMPLETED'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], max_length=255, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stock')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Returned Item',
                'verbose_name_plural': 'Returned Items',
                'unique_together': {('order', 'item')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='returned_item',
            field=models.ManyToManyField(related_name='returned_items', through='order.ReturnedItem', to='store.stock'),
        ),
    ]
