# Generated by Django 5.0.7 on 2024-07-31 10:46

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_remove_address_session_key_remove_order_session_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderNumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_items',
        ),
        migrations.AddField(
            model_name='order',
            name='second_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', length=16, max_length=32, prefix=''),
        ),
    ]
