# Generated by Django 5.0.7 on 2024-08-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_remove_address_session_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_reason',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('pending_for_pay', 'PENDING_FOR_PAY'), ('processing', 'PROCESSING'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('completed', 'COMPLETED'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='refund_reason',
            field=models.CharField(blank=True, choices=[('created', 'CREATED'), ('pending_for_pay', 'PENDING_FOR_PAY'), ('processing', 'PROCESSING'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('completed', 'COMPLETED'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], max_length=255, null=True),
        ),
    ]
