# Generated by Django 5.0.7 on 2024-07-31 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_delete_ordernumber_remove_order_ordered_items_and_more'),
        ('store', '0013_remove_wishlist_session_key_wishlist_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_reason',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ManyToManyField(related_name='order_items', through='order.OrderItem', to='store.stock'),
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('refund_reason', models.CharField(blank=True, choices=[('created', 'CREATED'), ('pending_for_pay', 'PENDING FOR PAY'), ('processing', 'PROCESSING'), ('delivering', 'DELIVERING'), ('delivered', 'DELIVERED'), ('completed', 'COMPLETED'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('cancelled', 'CANCELLED'), ('refunded', 'REFUNDED')], max_length=255, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.stock')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'Returned Item',
                'verbose_name_plural': 'Returned Items',
                'unique_together': {('order', 'item')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='returned_item',
            field=models.ManyToManyField(related_name='returned_items', through='order.ReturnedItem', to='store.stock'),
        ),
    ]
