# Generated by Django 5.0.3 on 2024-05-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('waiting_for_capture', 'WAITING_FOR_CAPTURE'), ('succeeded', 'SUCCEEDED'), ('canceled', 'CANCELLED')], default='pending', max_length=20)),
            ],
        ),
    ]
