# Generated by Django 5.1 on 2024-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(blank=True, null=True)),
                ('store_order_id', models.CharField(max_length=255)),
                ('store_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('waiting_for_capture', 'WAITING_FOR_CAPTURE'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('refunded', 'REFUNDED'), ('succeeded', 'SUCCEEDED'), ('canceled', 'CANCELLED')], max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
