# Generated by Django 5.0.3 on 2024-05-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_store_order_id_payment_store_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
