# Generated by Django 5.0.3 on 2024-06-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('waiting_for_capture', 'WAITING_FOR_CAPTURE'), ('partial_refunded', 'PARTIAL_REFUNDED'), ('refunded', 'REFUNDED'), ('succeeded', 'SUCCEEDED'), ('canceled', 'CANCELLED')], default='pending', max_length=20),
        ),
    ]
