# Generated by Django 5.0.3 on 2024-04-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_unique_together_cartitem_stock_and_more'),
        ('store', '0002_alter_color_name_alter_color_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'stock')},
        ),
    ]
