# Generated by Django 5.0.7 on 2024-08-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
