# Generated by Django 5.1 on 2024-08-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_stocks_cartitem_cart_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='stocks', to='cart.cartitem'),
        ),
    ]
