# Generated by Django 5.0.3 on 2024-04-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_anonymouscart_anonymouscartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymouscartitem',
            options={'verbose_name': 'Anonymous cart item', 'verbose_name_plural': 'Anonymous cart item'},
        ),
    ]
