# Generated by Django 5.0.3 on 2024-05-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_anonymouscartitem_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousCart',
        ),
        migrations.DeleteModel(
            name='AnonymousCartItem',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
