# Generated by Django 5.0.3 on 2024-04-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cartitem_id'),
        ('store', '0033_remove_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.itemsizecolor', verbose_name='Товар'),
        ),
    ]
