# Generated by Django 5.0.3 on 2024-04-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cartitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='quantity_in_cart',
        ),
    ]
