# Используем образ PostgreSQL
FROM postgres:latest

# Задаем переменные окружения
ENV POSTGRES_DB test_timshee_db
ENV POSTGRES_USER test_timshee
ENV POSTGRES_PASSWORD admin@123

# Указываем порт, на котором будет доступен PostgreSQL (по умолчанию 5432)
EXPOSE 5432