# Generated by Django 5.2.5 on 2025-08-12 09:33

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(help_text='Display name for this payment method', max_length=100, verbose_name='Method name')),
                ('payment_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('bank_transfer', 'Bank Transfer'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], max_length=20, verbose_name='Payment type')),
                ('provider', models.CharField(help_text='Payment gateway provider (stripe, paypal, etc.)', max_length=50, verbose_name='Payment provider')),
                ('provider_method_id', models.CharField(help_text='Payment method ID from the provider', max_length=255, verbose_name='Provider method ID')),
                ('is_default', models.BooleanField(default=False, help_text="Whether this is the user's default payment method", verbose_name='Is default')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active', verbose_name='Is active')),
                ('card_last_four', models.CharField(blank=True, help_text='Last 4 digits of the card number', max_length=4, verbose_name='Card last four digits')),
                ('card_brand', models.CharField(blank=True, help_text='Card brand (visa, mastercard, etc.)', max_length=20, verbose_name='Card brand')),
                ('card_exp_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Card expiration month')),
                ('card_exp_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Card expiration year')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from the payment provider', verbose_name='Metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Payment ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('RUB', 'Russian Ruble'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('requires_action', 'Requires Action'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20, verbose_name='Status')),
                ('gateway', models.CharField(help_text='Payment gateway used for this transaction', max_length=50, verbose_name='Payment gateway')),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID from the payment gateway', max_length=255, verbose_name='Gateway transaction ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Full response from the payment gateway', verbose_name='Gateway response')),
                ('description', models.TextField(blank=True, help_text='Description of what this payment is for', verbose_name='Description')),
                ('reference_id', models.CharField(blank=True, help_text='External reference ID (order ID, invoice ID, etc.)', max_length=255, verbose_name='Reference ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Payment processing fee', max_digits=10, verbose_name='Fee amount')),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount after fees', max_digits=10, null=True, verbose_name='Net amount')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='Authorized at')),
                ('captured_at', models.DateTimeField(blank=True, null=True, verbose_name='Captured at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Failed at')),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for payment failure', verbose_name='Failure reason')),
                ('failure_code', models.CharField(blank=True, help_text='Error code from payment gateway', max_length=100, verbose_name='Failure code')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment metadata', verbose_name='Metadata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentmethod', verbose_name='Payment method')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Refund ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Refund amount')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(blank=True, help_text='Reason for the refund', verbose_name='Refund reason')),
                ('gateway_refund_id', models.CharField(blank=True, help_text='Refund ID from the payment gateway', max_length=255, verbose_name='Gateway refund ID')),
                ('gateway_response', models.JSONField(blank=True, default=dict, verbose_name='Gateway response')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Failed at')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Failure reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Webhook ID')),
                ('gateway', models.CharField(max_length=50, verbose_name='Payment gateway')),
                ('event_type', models.CharField(help_text='Type of webhook event', max_length=100, verbose_name='Event type')),
                ('gateway_event_id', models.CharField(help_text='Event ID from the payment gateway', max_length=255, verbose_name='Gateway event ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='pending', max_length=20, verbose_name='Processing status')),
                ('payload', models.JSONField(help_text='Full webhook payload from the gateway', verbose_name='Webhook payload')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='HTTP headers from the webhook request', verbose_name='Webhook headers')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', verbose_name='Error message')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='payments.payment', verbose_name='Related payment')),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('intent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Intent ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('RUB', 'Russian Ruble'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('processing', 'Processing'), ('requires_capture', 'Requires Capture'), ('cancelled', 'Cancelled'), ('succeeded', 'Succeeded')], default='requires_payment_method', max_length=30, verbose_name='Status')),
                ('gateway', models.CharField(max_length=50, verbose_name='Payment gateway')),
                ('gateway_intent_id', models.CharField(blank=True, max_length=255, verbose_name='Gateway intent ID')),
                ('client_secret', models.CharField(blank=True, help_text='Secret for client-side payment confirmation', max_length=255, verbose_name='Client secret')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference_id', models.CharField(blank=True, max_length=255, verbose_name='Reference ID')),
                ('capture_method', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20, verbose_name='Capture method')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intent', to='payments.payment', verbose_name='Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment Intent',
                'verbose_name_plural': 'Payment Intents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_503f5b_idx'), models.Index(fields=['gateway', 'gateway_intent_id'], name='payments_pa_gateway_0f7852_idx'), models.Index(fields=['reference_id'], name='payments_pa_referen_f82967_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='payments_pa_user_id_61fd94_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['provider', 'provider_method_id'], name='payments_pa_provide_536827_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway', 'gateway_transaction_id'], name='payments_pa_gateway_d82ade_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_id'], name='payments_pa_referen_7b9331_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['payment', 'status'], name='payments_pa_payment_2735e7_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['gateway_refund_id'], name='payments_pa_gateway_e3a394_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['gateway', 'event_type'], name='payments_pa_gateway_6f185a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['gateway_event_id'], name='payments_pa_gateway_3430e1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhook',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_f210fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentwebhook',
            unique_together={('gateway', 'gateway_event_id')},
        ),
    ]
