# Generated by Django 5.2.5 on 2025-08-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of what the payment is for'),
        ),
    ]
