# Generated by Django 5.2.5 on 2025-08-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentintent',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
