# Generated by Django 5.2.5 on 2025-08-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentintent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, default='', help_text='External reference ID (order ID, invoice ID, etc.)', max_length=255, verbose_name='Reference ID'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='reference_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Reference ID'),
        ),
    ]
